theme: jekyll-theme-cayman
title: OpenMusic
description: Visual programming environment for computer-aided music compositon

zip_url: "https://github.com/openmusic-project/OM6/releases"

show_downloads: false

owner_url: https://github.com/j-bresson
site.github.owner_name: j-bresson
